// Generated by `xplat routes` — do not edit. Re-run after
// touching the route dir (add/remove/rename route files).
export type RouteName =
	| 'about'
	| 'changelog'
	| 'demo/:id'
	| 'detail'
	| 'list-nested-probe'
	| 'motion-probe'
	| 'notes'
	| 'parity'
	| 'private'
	| 'qa'

export interface RouteParams {
	'about': {  }
	'changelog': {  }
	'demo/:id': { id: string }
	'detail': {  }
	'list-nested-probe': {  }
	'motion-probe': {  }
	'notes': {  }
	'parity': {  }
	'private': {  }
	'qa': {  }
}

export interface RoutePresentations {
	'about': 'modal'
}
