// Generated by `xplat routes` — do not edit.
import { deriveRouteManifest, registerRoutes } from '@octane-xplat/ui'
import { bakedRouteData } from './routes.gen.data'
export type { RouteName, RouteParams, RoutePresentations } from './routes.gen.types'

const files = import.meta.glob(
	[
		'./app/**/*.{tsrx,tsx}',
		'!./app/**/*.mobile.{tsrx,tsx}',
		'!./app/**/*.ios.{tsrx,tsx}',
		'!./app/**/*.android.{tsrx,tsx}',
		'!./app/**/*.macos.{tsrx,tsx}',
		'!./app/**/*.windows.{tsrx,tsx}',
		'!./app/**/*.linux.{tsrx,tsx}'
	],
	{ eager: true },
)

export const routes = deriveRouteManifest(files, ['web'])
// Baked loader results ride the manifest — 'baked' route metas resolve
// against it at push time instead of running a loader.
routes.baked = bakedRouteData
registerRoutes(routes)
export const screens = routes.screens
