// Generated by `xplat routes` — baked loader results.
// Re-run `xplat routes` (or dev/build) after touching *.loader.* files.
export const bakedRouteData: Record<string, unknown> = {
	"changelog": {
		"version": "0.0.0",
		"entries": [
			{
				"version": "0.0.0",
				"note": "Baked loader output — computed at codegen"
			},
			{
				"version": "…",
				"note": "Earlier entries would come from a markdown/content dir"
			}
		]
	}
}
