// Generated by `xplat routes` — do not edit.
import { deriveRouteManifest, registerRoutes } from '@octane-xplat/ui'
export type { RouteName, RouteParams, RoutePresentations } from './routes.gen.types'

const files = import.meta.glob(
	[
		'./app/**/*.{tsrx,tsx}',
		'!./app/**/*.web.{tsrx,tsx}',
		'!./app/**/*.ios.{tsrx,tsx}',
		'!./app/**/*.android.{tsrx,tsx}',
		'!./app/**/*.mobile.{tsrx,tsx}',
		'!./app/**/*.windows.{tsrx,tsx}',
		'!./app/**/*.linux.{tsrx,tsx}'
	],
	{ eager: true },
)

export const routes = deriveRouteManifest(files, ['macos'])
registerRoutes(routes)
export const screens = routes.screens
