// Generated by `xplat routes` — do not edit. Re-run after
// touching the route dir (add/remove/rename route files).
export type RouteName = 
	| 'demo/:id'
	| 'detail'

export interface RouteParams {
	'demo/:id': { id: string }
}

export interface RoutePresentations {
	// no +modal/+fade routes
}
