// Generated by `xplat routes` — baked loader results.
// Re-run `xplat routes` (or dev/build) after touching *.loader.* or .md routes.
export const bakedRouteData: Record<string, unknown> = {
	"notes": {
		"kind": "octane-xplat/md",
		"v": 1,
		"children": [
			{
				"t": "h",
				"depth": 1,
				"children": [
					{
						"t": "text",
						"text": "Release Notes"
					}
				]
			},
			{
				"t": "p",
				"children": [
					{
						"t": "text",
						"text": "Markdown routes bake at codegen — this file's AST ships in the bundle and\nrenders through the shared vocabulary on web and native."
					}
				]
			},
			{
				"t": "h",
				"depth": 2,
				"children": [
					{
						"t": "text",
						"text": "How it works"
					}
				]
			},
			{
				"t": "list",
				"ordered": false,
				"items": [
					[
						{
							"t": "code",
							"text": "xplat routes"
						},
						{
							"t": "text",
							"text": " parses the file at build time"
						}
					],
					[
						{
							"t": "text",
							"text": "The AST lands in "
						},
						{
							"t": "code",
							"text": "routes.gen.data.ts"
						}
					],
					[
						{
							"t": "code",
							"text": "<MarkdownScreen>"
						},
						{
							"t": "text",
							"text": " renders it — no parser at runtime"
						}
					]
				]
			},
			{
				"t": "list",
				"ordered": true,
				"items": [
					[
						{
							"t": "text",
							"text": "Ordered lists work too"
						}
					],
					[
						{
							"t": "text",
							"text": "As do "
						},
						{
							"t": "code",
							"text": "code spans"
						},
						{
							"t": "text",
							"text": " and "
						},
						{
							"t": "bold",
							"children": [
								{
									"t": "text",
									"text": "bold"
								}
							]
						},
						{
							"t": "text",
							"text": " text"
						}
					]
				]
			},
			{
				"t": "code",
				"text": "code blocks stay mono"
			},
			{
				"t": "quote",
				"children": [
					{
						"t": "text",
						"text": "Blockquotes flatten to muted text in v1."
					}
				]
			}
		]
	},
	"changelog": {
		"version": "0.0.0",
		"entries": [
			{
				"version": "0.0.0",
				"note": "Baked loader output — computed at codegen"
			},
			{
				"version": "…",
				"note": "Earlier entries would come from a markdown/content dir"
			}
		]
	}
}
