// Generated by `xplat routes` — do not edit.
import { Device } from '@nativescript/core'
import { deriveRouteManifest, registerRoutes } from '@octane-xplat/ui'
export type { RouteName, RouteParams, RoutePresentations } from './routes.gen.types'

const files = import.meta.glob(
	[
		'./app/**/*.{tsrx,tsx}',
		'!./app/**/*.web.{tsrx,tsx}',
		'!./app/**/*.macos.{tsrx,tsx}',
		'!./app/**/*.windows.{tsrx,tsx}',
		'!./app/**/*.linux.{tsrx,tsx}'
	],
	{ eager: true },
)

export const routes = deriveRouteManifest(files, Device.os === 'Android' ? ['android', 'mobile'] : ['ios', 'mobile'])
registerRoutes(routes)
export const screens = routes.screens
