import { command, option, optional, string } from '@alloc/cmd-ts'
import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import * as p from '@clack/prompts'

// Mirror of packages/ui/src/route-table.ts conventions — the CLI walks the
// route dir off disk (no vite glob), so the derivation is re-implemented
// here. Keep the two in sync: same suffix strip order, same index/_layout
// rules. All platform variants count — the union is cross-platform.
const EXT = /\.(tsrx|tsx|ts|mts|cts|js|mjs|cjs|jsx)$/
const SUFFIX = /\.(web|mobile|ios|android|macos|windows|linux)$/
const PARAM = /^\[(.+)\]$/
const PRESENT = /\+(modal|fade|push)$/

function walk(dir, out = []) {
	for (const name of readdirSync(dir).sort()) {
		const full = join(dir, name)
		if (statSync(full).isDirectory()) {
			walk(full, out)
		} else if (EXT.test(name)) {
			out.push(full)
		}
	}

	return out
}

function routeFor(rel) {
	rel = rel.split(sep).join('/').replace(EXT, '')
	const parts = rel.split('/')
	let base = parts[parts.length - 1]
	const sm = SUFFIX.exec(base)
	if (sm) {
		base = base.slice(0, base.length - sm[0].length)
	}

	const pm = PRESENT.exec(base)
	const presentation = pm ? pm[1] : undefined
	if (pm) {
		base = base.slice(0, base.length - pm[0].length)
	}

	if (base === '_layout') {
		return null
	}

	const segs = parts.slice(0, -1).concat(base)
	if (segs[segs.length - 1] === 'index') {
		segs.pop()
	}

	const segments = segs.map((s) => {
		const m = PARAM.exec(s)
		return m ? ':' + m[1] : s
	})

	return {
		name: segments.join('/') || 'index',
		params: segments.filter((s) => s.startsWith(':')).map((s) => s.slice(1)),
		presentation,
	}
}

/** Generates routes.gen.types.ts + platform manifest glue for a route dir.
 *  Returns true when a dir was found and files written; false when no route
 *  dir exists (callers that run this implicitly — dev/build — stay quiet). */
export function generateRoutes(cwd, dir, out) {
	if (!dir) {
		return false
	}

	// `out` is the module basename — shared types and target manifests are emitted:
	//   <out>.types.ts    shared types (RouteName/Params/Presentations)
	//   <out>.web.ts      web glob + registerRoutes
	//   <out>.mobile.ts  mobile glob + registerRoutes (Device.os prefer)
	//   <out>.macos.ts   AppKit glob + registerRoutes (macos prefer)
	// Importing '<out>' resolves the platform leaf automatically.
	const base = (out ?? join(dir, '..', 'routes.gen')).replace(/\.ts$/, '')

	// name → {params, presentation}; platform variants of one route
	// collapse to a single entry (union across platforms).
	const seen = new Map()
	const routePaths = []
	for (const file of walk(join(cwd, dir))) {
		const routePath = relative(join(cwd, dir), file).split(sep).join('/')
		if (/\.(tsrx|tsx)$/.test(routePath)) {
			routePaths.push(routePath)
		}

		const r = routeFor(routePath)
		if (!r) {
			continue
		}

		if (!seen.has(r.name)) {
			seen.set(r.name, r)
		}
	}

	const list = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name))

	const union = list.length ? list.map((r) => `\n\t| '${r.name}'`).join('') : 'never'

	const params = list.map(
		(r) => `\t'${r.name}': { ${r.params.map((k) => `${k}: string`).join('; ')} }`,
	)

	const presents = list
		.filter((r) => r.presentation)
		.map((r) => `\t'${r.name}': '${r.presentation}'`)

	const src = `// Generated by \`xplat routes\` — do not edit. Re-run after
// touching the route dir (add/remove/rename route files).
export type RouteName =${union}

export interface RouteParams {
${params.length ? params.join('\n') : '\t// no param routes'}
}

export interface RoutePresentations {
${presents.length ? presents.join('\n') : '\t// no +modal/+fade routes'}
}
`

	writeFileSync(join(cwd, base + '.types.ts'), src)

	// Platform-suffixed twins carry the actual manifest derivation +
	// registration — routes.gen.web.ts / routes.gen.mobile.ts resolve
	// through the platform extension chain, so importing './routes.gen'
	// gets the right glob for the platform with no app-side leaf file.
	// Types live in '.types.ts' — './routes.gen' inside a .web.ts sibling
	// would self-resolve.
	const outDir = join(cwd, base, '..')
	const rel = relative(outDir, join(cwd, dir)).split(sep).join('/')
	const globDir = rel.startsWith('.') ? rel : './' + rel
	const baseName = base.split('/').pop()
	const typesRef = `export type { RouteName, RouteParams, RoutePresentations } from './${baseName}.types'`
	const platformSuffix = /\.(web|mobile|ios|android|macos|windows|linux)\.(tsrx|tsx)$/
	const specializedPaths = new Map()
	for (const path of routePaths) {
		const match = platformSuffix.exec(path)
		if (!match) {
			continue
		}

		const plainPath = path.slice(0, -match[0].length) + `.${match[2]}`
		const paths = specializedPaths.get(match[1]) ?? new Set()
		paths.add(plainPath)
		specializedPaths.set(match[1], paths)
	}
	const plainPaths = routePaths.filter((path) => !platformSuffix.test(path))
	const globLiteral = (path) => path.replace(/[\\*?{}()!@+\[\]]/g, '\\$&')
	const exactExclusions = (suffix) => {
		const specialized = specializedPaths.get(suffix)
		return [...(specialized ?? [])]
			.filter((path) => plainPaths.includes(path))
			.map((path) => `\t\t'!${globDir}/${globLiteral(path)}'`)
	}

	const shared = (prelude, globs, prefer) => `// Generated by \`xplat routes\` — do not edit.
${prelude}import { deriveRouteManifest, registerRoutes } from '@octane-xplat/ui'
${typesRef}

const files = import.meta.glob(
	[
		'${globDir}/**/*.{tsrx,tsx}',
${globs}
	],
	{ eager: true },
)

export const routes = deriveRouteManifest(files, ${prefer})
registerRoutes(routes)
export const screens = routes.screens
`

	writeFileSync(
		join(cwd, base + '.web.ts'),
		shared(
			'',
			[
				`\t\t'!${globDir}/**/*.mobile.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.ios.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.android.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.macos.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.windows.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.linux.{tsrx,tsx}'`,
				...exactExclusions('web'),
			].join(',\n'),
			`['web']`,
		),
	)

	writeFileSync(
		join(cwd, base + '.mobile.ts'),
		shared(
			`import { Device } from '@nativescript/core'\n`,
			[
				`\t\t'!${globDir}/**/*.web.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.macos.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.windows.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.linux.{tsrx,tsx}'`,
			].join(',\n'),
			`Device.os === 'Android' ? ['android', 'mobile'] : ['ios', 'mobile']`,
		),
	)

	writeFileSync(
		join(cwd, base + '.macos.ts'),
		shared(
			'',
			[
				`\t\t'!${globDir}/**/*.web.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.ios.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.android.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.mobile.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.windows.{tsrx,tsx}'`,
				`\t\t'!${globDir}/**/*.linux.{tsrx,tsx}'`,
				...exactExclusions('macos'),
			].join(',\n'),
			`['macos']`,
		),
	)

	return list.length
}

export const routes = command({
	name: 'routes',
	description: 'Generate routes.gen.ts (typed RouteName/params) from the route dir',
	args: {
		dir: option({
			long: 'dir',
			short: 'd',
			type: optional(string),
			description: 'Route dir — default: first of ./app, ./src/app',
		}),
		out: option({
			long: 'out',
			short: 'o',
			type: optional(string),
			description: 'Output file — default: <route dir>/../routes.gen.ts',
		}),
	},
	handler: async (args) => {
		const cwd = process.cwd()
		const dir = args.dir ?? ['app', 'src/app'].find((d) => existsSync(join(cwd, d)))
		if (!dir) {
			p.log.error('No route dir found — expected ./app or ./src/app (or pass --dir).')
			process.exit(1)
		}

		const count = generateRoutes(cwd, dir, args.out)
		p.log.success(
			`Wrote routes.gen.{types,web,mobile,macos}.ts — ${count} route${count === 1 ? '' : 's'}`,
		)
	},
})
