import { command, option, optional, string } from '@alloc/cmd-ts'
import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import * as p from '@clack/prompts'

// Mirror of packages/ui/src/route-table.ts conventions — the CLI walks the
// route dir off disk (no vite glob), so the derivation is re-implemented
// here. Keep the two in sync: same suffix strip order, same index/_layout
// rules. All platform variants count — the union is cross-platform.
const EXT = /\.(tsrx|tsx|ts|mts|cts|js|mjs|cjs|jsx)$/
const SUFFIX = /\.(web|native|ios|android)$/
const PARAM = /^\[(.+)\]$/
const PRESENT = /\+(modal|fade|push)$/

function walk(dir, out = []) {
	for (const name of readdirSync(dir).sort()) {
		const full = join(dir, name)
		if (statSync(full).isDirectory()) walk(full, out)
		else if (EXT.test(name)) out.push(full)
	}

	return out
}

function routeFor(rel) {
	rel = rel.split(sep).join('/').replace(EXT, '')
	const parts = rel.split('/')
	let base = parts[parts.length - 1]
	const sm = SUFFIX.exec(base)
	if (sm) base = base.slice(0, base.length - sm[0].length)
	const pm = PRESENT.exec(base)
	const presentation = pm ? pm[1] : undefined
	if (pm) base = base.slice(0, base.length - pm[0].length)
	if (base === '_layout') return null
	const segs = parts.slice(0, -1).concat(base)
	if (segs[segs.length - 1] === 'index') segs.pop()
	const segments = segs.map((s) => {
		const m = PARAM.exec(s)
		return m ? ':' + m[1] : s
	})

	return {
		name: segments.join('/') || 'index',
		params: segments.filter((s) => s.startsWith(':')).map((s) => s.slice(1)),
		presentation,
	}
}

export const routes = command({
	name: 'routes',
	description: 'Generate routes.gen.ts (typed RouteName/params) from the route dir',
	args: {
		dir: option({
			long: 'dir',
			short: 'd',
			type: optional(string),
			description: 'Route dir — default: first of ./app, ./src/app',
		}),
		out: option({
			long: 'out',
			short: 'o',
			type: optional(string),
			description: 'Output file — default: <route dir>/../routes.gen.ts',
		}),
	},
	handler: async (args) => {
		const cwd = process.cwd()
		const dir = args.dir ?? ['app', 'src/app'].find((d) => existsSync(join(cwd, d)))
		if (!dir) {
			p.log.error('No route dir found — expected ./app or ./src/app (or pass --dir).')
			process.exit(1)
		}

		const out = args.out ?? join(dir, '..', 'routes.gen.ts')

		// name → {params, presentation}; platform variants of one route
		// collapse to a single entry (union across platforms).
		const seen = new Map()
		for (const file of walk(join(cwd, dir))) {
			const r = routeFor(relative(join(cwd, dir), file))
			if (!r) continue
			if (!seen.has(r.name)) seen.set(r.name, r)
		}

		const list = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name))

		const union = list.length
			? list.map((r) => `\n\t| '${r.name}'`).join('')
			: 'never'

		const params = list
			.filter((r) => r.params.length)
			.map((r) => `\t'${r.name}': { ${r.params.map((k) => `${k}: string`).join('; ')} }`)

		const presents = list
			.filter((r) => r.presentation)
			.map((r) => `\t'${r.name}': '${r.presentation}'`)

		const src = `// Generated by \`xplat routes\` — do not edit. Re-run after
// touching the route dir (add/remove/rename route files).
export type RouteName = ${union}

export interface RouteParams {
${params.length ? params.join('\n') : '\t// no param routes'}
}

export interface RoutePresentations {
${presents.length ? presents.join('\n') : '\t// no +modal/+fade routes'}
}
`

		writeFileSync(join(cwd, out), src)
		p.log.success(`Wrote ${out} — ${list.length} route${list.length === 1 ? '' : 's'}`)
	},
})
