import { command, option, optional, string, subcommands } from '@alloc/cmd-ts'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { join, resolve } from 'node:path'

export async function initializeUpdates(root) {
	// Resolve the optional runtime from the app, never from the CLI's own dependencies.
	createRequire(join(root, 'package.json')).resolve('@octane-xplat/updates/prepare')
	const folder = join(root, 'hooks/after-prepare')
	const destination = join(folder, 'xplat-updates.cjs')
	const hook = `// Generated by xplat updates init. Commit this hook with your app.\nmodule.exports = function (hookArgs) {\n\tconst projectDir = hookArgs.projectData.projectDir\n\tconst platform = hookArgs.platformData?.platformName ?? hookArgs.prepareData?.platform\n\treturn require('@octane-xplat/updates/prepare')({ projectDir, platform })\n}\n`
	let existing
	try {
		existing = await readFile(destination, 'utf8')
	} catch (error) {
		if (error.code !== 'ENOENT') {throw error}
	}

	if (existing && existing !== hook)
		{throw new Error('Existing OTA hook differs; reconcile it before running updates init')}

	await mkdir(folder, { recursive: true })
	await writeFile(destination, hook)
	return destination
}

const init = command({
	name: 'init',
	description:
		'Wire the optional OTA runtime into iOS/Android native boot; rebuild both binaries afterwards',
	args: {
		dir: option({ type: optional(string), long: 'dir', description: 'App root (default: cwd)' }),
	},
	handler: async ({ dir }) => {
		const file = await initializeUpdates(resolve(dir ?? '.'))
		console.log(`Created ${file}. Commit the hook and rebuild your iOS/Android binaries.`)
	},
})

export const updates = subcommands({
	name: 'updates',
	description: 'Configure optional native OTA updates',
	cmds: { init },
})
